version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=boilerplate-db
    ports:
      - "5436:5432"
    volumes:
      - ./dbData/:/var/lib/postgresql/data